### ISSUE TITLE
failed installation

### ISSUE THREAD

**Issue by xXDeathAbyssXx** [iamverysimp1e/dots#11]
I did all the steps correctly as it appears in the readme, I already saw that there were some errors in the typos of some packages but I did this today, February 6, so there shouldn't be any errors in the readme commands.

**Problem**: The arch with gnome works correctly, but when I log in to hyperland I only see the wallpaper and when using "ctrl + alt + f2" the computer freezes, which doesn't let me test.

`.config` **dir**:

```bash
dconf
dleyna-renderer-service.conf
dunst
epiphany
evolution
eww
FireFox
gnome-session
goa-1.0
gtk-3.0
gtk-4.0
hypr
ibus
kitty
nautilus
pavucontrol.ini
pulse
rofi
spicetify
swaylock
user-dirs.dirs
user-dirs.locale
waybar
WebCord
yay
```

**Notes**: I am not an expert in rice, but for the same reason I must clarify that I tried in gnome "since I cannot enter hyperland" open rofi with the console and it opened with the theme but it did not let me move with the keyboard or write, just use the mouse wheel doesn't even click, I repeat I'm not an expert in rice so I don't know if rofi not being in hyperland doesn't work correctly, I also saw in gnome that the color of the kitty changed correctly.

**Comment by iamverysimp1e** [comment]
what do you mean when using the ctrl + alt + f2? . Also, about the kitty terminal themes changed. I haven't used GNOME in a while like a couple months ago and now hyprland is my main WM.

**Comment by xXDeathAbyssXx** [comment]
> what do you mean when using the ctrl + alt + f2?

R/ Is to open de tty.

>  Also, about the kitty terminal themes changed. I haven't used GNOME in a while like a couple months ago and now hyprland is my main WM.

R/ I don't know what you mean, sorry if I don't explain myself well since I don't speak English natively, what I commented was that apparently the kitty is fine, and I don't want to use gnome, it's just the only way to use my arch since hyperland does not work with the problem you mentioned, that only the wallpaper is visible.

**Comment by xXDeathAbyssXx** [comment]
> hmmmmm, why it is not working
R/ I'm new and I really don't know, although if I could test I would but I can't open tty|

>  So you want hyprland as your main WM right?? Im confused about ur ans
R/ I mean, I installed arch with the archinstall command and I chose gnome to navigate and install everything from the GUI because I'm not an expert, after that I did all the steps from gnome and when I restart the pc and log in to hyperland that happens

**Comment by iamverysimp1e** [comment]
hmmmm did you follow the [hyprland installatino guide](https://wiki.hyprland.org/Getting-Started/Installation/)

**Comment by iamverysimp1e** [comment]
actually u dont need to install all of that dependencies just `yay -S hyprland-git` thats all

**Comment by xXDeathAbyssXx** [comment]
> actually u dont need to install all of that dependencies just `yay -S hyprland-git` thats all

Yes, i follow the guide.

**Comment by iamverysimp1e** [comment]
Does it work ?

**Comment by xXDeathAbyssXx** [comment]
> Does it work ?

that was my first try, so it doesn't work, my second try was to install all those packages and reinstall hyperland.

**Comment by iamverysimp1e** [comment]
Just remove all the available wm you had on your machine then install `sddm` and do as my manual said
