### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by NextWork123** [iamverysimp1e/dots#6]
Hello,i'm using a distro based on arch linux (cachyos) with hyprland. The script of waybar "weather.py" give this error i don't know how to fix 
```
Traceback (most recent call last):
  File "/home/next/.config/waybar/scripts/weather.py", line 47, in <module>
    status_code = html_data("#regionHeader").attr("class").split(" ")[2].split("-")[2]
AttributeError: 'NoneType' object has no attribute 'split' 
```

I hope you can help me to fix that.

**Comment by iamverysimp1e** [comment]
I got that script on another post, currently updating that weather script.

**Comment by NextWork123** [comment]
Ok thanks.

**Comment by iamverysimp1e** [comment]
ok thanks alot
