### ISSUE TITLE
Hyprland Eww bar command typo

### ISSUE THREAD

**Issue by ryohkhn** [iamverysimp1e/dots#8]
There's a typo on the packages ```coreutils``` and ```findutils``` in the Eww bar command for Hyprland

**Comment by iamverysimp1e** [comment]
hmmmm, i didn't get it. Could you explain more details ??

**Comment by ryohkhn** [comment]
Line 72 in the readme:  
```
  yay -S bc blueberry bluez coreutlis dbus findutlis gawk gnunet jaq light networkmanager network-manager-applet pavucontrol playerctl procps ripgrep socat udev upower util-linux wget wireplumber wlogout eww-wayland
  ```
The packages ```coreutlis``` and ```findutlis``` should be  ```coreutils``` and ```findutils```, there's a typo on the names !

**Comment by iamverysimp1e** [comment]
ohhhhh, i got it thanks!!! might update the Readme later
